apiVersion: apps/v1
kind: Deployment
metadata:
    name: playlist
spec:
    replicas: 2
    selector:
        matchLabels:
            app: spotifyre-playlist
    template:
        metadata:
            labels:
                app: spotifyre-playlist
        spec:
            containers:
                - name: spotifyre-playlist
                  image: tejas1812/spotifyre-playlist:v8
                  imagePullPolicy: Always
                  envFrom:
                  - secretRef:
                      name: credentials
                  ports:
                      - containerPort: 5000
                  resources:
                      limits:
                          memory: "1024Mi"
                          cpu: "1000m"