 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/polished-time-381400/web-ui-app:$COMMIT_SHA', './web_ui_app']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/polished-time-381400/web-ui-app:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'web-ui-app'
   - '--image'
   - 'gcr.io/polished-time-381400/web-ui-app:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
 images:
 - 'gcr.io/polished-time-381400/web-ui-app:$COMMIT_SHA'