apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-backend
  template:
    metadata:
      labels:
        app: login-backend
    spec:
      containers:
        - name: login-backend
          image: login-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://<username>:<password>@<host>/<database>
