apiVersion: apps/v1
kind: Deployment
metadata:
    name: login-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: login-backend
    template:
        metadata:
            labels:
                app: login-backend
        spec:
            containers:
                - name: login-backend
                  image: 
                  imagePullPolicy: Always
                  envFrom:
                  - secretRef:
                      name: credentials
                  ports:
                      - containerPort: 5000
                  