apiVersion: v1
kind: Service
metadata:
  name: login-backend-service
spec:
  selector:
    app: login-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer
